name: CMake

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/*'
      - 'editor/**'
      - 'ComponentPrecompiler/**'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake (Game Only)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DBUILD_EDITOR=OFF

    - name: Build Minigin
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}} --target minigin

